language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pipenv install 
# command to run tests
script:
  - python backend/graphql-backend.py
  - python backend/functions.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
