version: "3.8"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE={MYSQLDATABASE:-covidbot}
      - MYSQL_ROOT_PASSWORD=${MYSQLPASSWORD:-cmPNTHqENRY3A5ABnQ9BNsTjof6STbKg}
    ports:
      - '3306:3306'
  
  memcached:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11211:11211'
  covidbot_app:
    environment:
      - PORT=${PORT:-8000}
      - MYSQLHOST=${MYSQLHOST:-localhost}
      - MYSQLPORT=${MYSQLPORT:-3306}
      - MYSQLUSER=${MYSQLUSER:-mysql}
      - MYSQLPASSWORD=${MYSQLPASSWORD:-cmPNTHqENRY3A5ABnQ9BNsTjof6STbKg}
      - MYSQLDATABASE=${MYSQLDATABASE:-covidbot}
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8000:8000'

